FROM alfuerst/action-python-v3.6-ai

RUN apt-get install -y coreutils
RUN python -m pip install --upgrade pip
RUN apt-get install -y libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apt-get install -y jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev